_posts/2016-01-12-cpp-01.md, _posts/2016-01-12-cpp-02.md, _posts/2016-01-12-cpp-03.md, _posts/2016-01-12-cpp-04.md
I changed the namespace in the code, but forgot about the tutorials...
=> fix typos and inconsistencies in cpp tutorials

_posts/2015-06-13-accessing-pmem.md
I assume this is just a typo. See the example (https://github.com/pmem/nvml/blob/master/src/examples/libpmemobj/string_store/writer.c#L68) as a reference.
Anyway, I want to thank you for this project and particularly the tutorial posts which makes it incredible easy for an novice as me to get started. :heart:
=> Use `rootp` in blog post

_posts/2014-09-23-btt.md
Fix display of headings. http://pmem.io/2014/09/23/btt.html has broken
headings displaying the markdown hases in front of them. Add a space between
the hashes and the heading so Jekyll understands it.
Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
=> 2014-09-23-btt.md: Fix display of headings

_posts/2016-05-10-cpp-05.md, _posts/2016-05-19-cpp-06.md
There is a slight but significant difference in atomic/transactional
deallocation that needs to be clarified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/40)
=> cpp: clarify object destruction on deletion

_posts/2016-05-25-cpp-07.md
Misspelled transaction::automatic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/45)
=> cpp: fix typos in post

_posts/2016-02-22-pm-emulation.md
Add link to info about  how to choose the correct memmap kernel parameter for pmem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/54)
=> update: info about  how to choose the correct memmap kernel parameter

_posts/2017-01-23-cpp-strings.md
Minor correction to sample persistent string class included in this post.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/57)
=> cpp: modeling strings post, correction

about/index.md
This fixes a broken link to Documents on the About page: http://pmem.io/Documents/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/73)
=> Fix link to documents page

README.md, _layouts/default.html
ndctl man pages are now available online at pmem.github.io/ndctl via the
gh-pages branch in the ndctl repo. Add a link to this from the top nav
bar in pmem.io, and update the readme to talk about ndctl/gh-pages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/74)
=> Add an ndctl redirect to the pmem.io top bar

_posts/2018-06-25-fio-tutorial.md
I've corrected bold font, removed unnecessary bullet point before "either you choose", added new line signs when necessary and changed "ini" highlighting to "bash", since the first one wasn't coloring correctly FIO syntax.
This time I've tested changes on my repository, so it should work fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/80)
=> Fixing styling issues of FIO blog post

_posts/2014-09-09-git-workflow.md
Adding info about squashing your commits after review to git-workflow blog
you can see how it looks here:
https://lukaszstolarczuk.github.io/2014/09/09/git-workflow.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/87)
=> add info for squashing commits after review

_posts/2019-02-20-cpp-vector.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/97)
=> fix typos in pmem::obj::vector blog

_posts/2019-02-01-pool-conversion-tool.md
fix broken link in 'Pool conversion tool' blog post
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/99)
=> blog: link fix in pmdk-convert post

book/index.html
Social Media sharing through LinkedIn, Facebook, and others relies on the OpenGraph metadata or it'll fall back to scraping the site.  I've added the `<meta property='og:* ...>` tags to ensure social media cralwers obtain the correct information when visitors share the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/108)
=> Added Open Graph Metadata for Crawlers and Social Media Sharing

repoindex.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/111)
=> fix typo in rpmem library name

_layouts/default.html, _layouts/post.html, _layouts/redirect.html, css/pmem.css
I've noticed that an average session duration of a phone user on our website is significantly (50%) shorter than that of a PC or a tablet user.
I'm guessing this might have something to do with our website not displaying very well on mobile devices, so I've changed a few things so that at least the main body of a blog post doesn't have to be scrolled horizontally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/131)
=> basic responsive design

repoindex.md
since pmemkv-java 1.0 release, pmemkv-jni is moving to archive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/139)
=> move pmemkv-jni to inactive in repoindex

_posts/2020/2020-03-04-pmemkv-bindings.md
Word "sub-module" in context of repository content indicate git submodules
which may be misleading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/144)
=> pmemkv bindings: fix java binding implementation detail

book/index.html, book/js/custom.js
Marketing has changed from StackOverflow to Cafelli. New pixel code is required. 
Also added a link to "[Developer Tips and Tricks for Persistent Memory](https://software.intel.com/content/www/us/en/develop/articles/developer-tips-and-tricks-for-persistent-memory.html)" on the download page so the visitor has a quick introduction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/148)
=> [Book] Add Cafelli pixel tracking for Stack Overflow advertising campaign

_posts/2016/2016-02-22-pm-emulation.md
Newer xfs versions have a data block sharing feature. That feature is incompatible with DAX. This PR updates the blog post accordingly.
See also:
https://kb.pmem.io/problem/100000005-Mounting-a-DAX-XFS-file-system-can-return-wrong-fs-type,-bad-option,-bad-superblock,-missing-code-page-or-helper-program/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/149)
=> PM Emulation: Add reflink=0 for xfs

_posts/2015/2015-07-17-pmemcheck-basic.md, _posts/2015/2015-07-20-pmemcheck-transactions.md
it's better to use generated version than a link to raw docs.
Remove also personal contact point and use only "issues" for troubleshooting.
// FYI, we don't seem to have any links (on pmem.io) to the pmem.io/valgrind sub-section; not sure if we want to, though 😉
// preview of updated blog posts:
https://lukaszstolarczuk.github.io/2015/07/17/pmemcheck-basic.html
https://lukaszstolarczuk.github.io/2015/07/20/pmemcheck-transactions.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/163)
=> blog posts: update links to pmemcheck docs

_posts/2021/2021-09-17-concurrency.md
This post is meant to describe problems with concurrency programming and serve as an introduction to the blog post about concurrent_hash_map and concurrent_map which we are working on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/160)
=> Add blog post about concurrency considerations

data/en/dev_hub.yml
"Learn more" links on this page are broken for PMDK and pmemkv:
https://pmem.io/developer-hub/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/170)
=> fix links to pmdk and pmemkv in devhub

content/rpma/_index.md
Fix links to man pages (use temporary ones)
and add man pages for v0.10.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/195)
=> rpma: fix links to man pages, add man pages for v0.10.0

config.toml, content/announcements/2022/MiniAsync-v0-1-0-release.md, content/announcements/2022/pmemstream-v0-2-0-release.md, content/blog/2022/pmemstream-intro.md, content/miniasync/_index.md, content/pmemkv/_index.md, content/pmemstream/_index.md, data/en/miniasync.yml, data/en/pmemstream.yml, static/css/custom.css, themes/pmem-hugo/layouts/miniasync/list.html, themes/pmem-hugo/layouts/miniasync/single.html, themes/pmem-hugo/layouts/pmemstream/list.html, themes/pmem-hugo/layouts/pmemstream/single.html
Preview:
- https://lukaszstolarczuk.github.io/pmemstream/
- https://lukaszstolarczuk.github.io/miniasync/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/260)
at least 2 links from https://github.com/pmem/pmem.github.io/issues/200 are updated by this PR :)
=> Add new sub pages (for stream and miniasync)

static/css/custom.css
https://pmem.io/blog/2020/01/introduction-to-libmemkind/
https://lukaszstolarczuk.github.io/blog/2020/01/introduction-to-libmemkind/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/278)
=> add extra space after code block, before next content

content/announcements/2022/pmemstream-v0-2-0-release.md, data/en/pmemstream.yml
- better image
- correct manpages' paths
https://lukaszstolarczuk.github.io/announcements/2022/pmemstream-v0-2-0-release/
https://lukaszstolarczuk.github.io/pmemstream/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/282)
=> update pmemstream manpages path and image

content/pmdk/librpmem.md, data/en/pmdk.yml
- add deprecation and librpma notes,
- set fixed links to v1.12 (master branch will not contain librpmem soon).
// This change will be needed when https://github.com/pmem/pmdk/pull/5495 is merged... but it can actually be merged now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/312)
=> librpmem content update

content/pmdk/libpmempool.md, content/pmdk/pmempool.md, data/en/pmdk.yml
including cleaning up, adding missing links to the latest release, and removing redundant content (like repeated examples).
// Before:
https://pmem.io/pmdk/libpmempool/
https://pmem.io/pmdk/pmempool/
// After:
https://lukaszstolarczuk.github.io/pmdk/libpmempool/
https://lukaszstolarczuk.github.io/pmdk/pmempool/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/313)
=> (lib)pmempool content description update

content/blog/2022/update-pmdk-project-status.md
https://github.com/pmem/pmdk/pull/5495
https://github.com/pmem/pmdk/pull/5513
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/326)
=> remove mention of librpmem and libpmemset from the blog

content/blog/2018/fio-tutorial.md
pmemblk engine is not available in FIO anymore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/333)
=> update FIO blog post

content/blog/2022/update-pmdk-project-status.md
syscall_intercept has a new, external maintainer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/332)
=> Update blog post with PMDK's future

content/blog/2015/obj-mysql.md, content/blog/2015/pmemcheck-transactions.md, content/blog/2015/pmemobjfs.md, content/blog/2015/transactions.md, content/blog/2015/tx-alloc.md, content/blog/2015/type-safety-macros.md, content/blog/2015/types.md, content/blog/2016/cpp-03.md, content/blog/2016/cpp-06.md, content/blog/2016/cpp-07.md, content/blog/2016/cpp-08.md, content/blog/2016/cpp-ctree-conversion.md, content/blog/2016/windows-nvml.md, content/blog/2017/cpp-containers.md, content/blog/2017/pmemkv-zero-copy-leaf-splits.md
Due to a change of engine (for generating website's content), some 'chars' were improperly formatted - it especially broke code snippets. It's another and last part of fixes in this area.
Fixes: #270
// Preview (example blog post):
before: https://pmem.io/blog/2017/07/using-standard-library-containers-with-persistent-memory/
after: https://lukaszstolarczuk.github.io/blog/2017/07/using-standard-library-containers-with-persistent-memory/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/335)
=> fix blog posts' formatting

content/pmdk/libpmemblk.md, data/en/pmdk.yml, data/en/repoindex.yml
https://github.com/pmem/pmdk/pull/5538
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/338)
=> pmdk: set libpmemblk as deprecated

themes/pmem-hugo/layouts/pmdk/single.html
Preview:
before:
https://pmem.io/pmdk/librpmem/
https://pmem.io/pmdk/libpmemset/
after:
https://lukaszstolarczuk.github.io/pmdk/librpmem/
https://lukaszstolarczuk.github.io/pmdk/libpmemset/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/349)
=> pmdk: remove table with manpages link for removed libs

content/announcements/2022/Memkind-v1-14-0-release.md, content/announcements/2023/PMDK-v1-13-0-release.md, content/announcements/2023/PMDK-v1-13-1-release.md, content/announcements/2023/customer-letter-march-2023.md, themes/pmem-hugo/layouts/partials/content/announcements.html
Note: It supersedes 1.13.0 as the featured announcement.
Preview:
- https://janekmi.github.io (featured announcements) and
- https://janekmi.github.io/announcements/2023/pmdk-v1-13-1-release/ (the 1.13.1 announcement).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/359)
=> Add PMDK 1.13.1 announcement and fix the featured announcement logic

data/en/pmdk.yml, themes/pmem-hugo/layouts/pmdk/list.html
Requires:
Preview:
https://grom72.github.io/pmdk/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/367)
=> Pmdk summary

content/pmdk/pmempool.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/370)
=> Update pmempool.md to point version 1.13 instead of 1.12

data/en/homepage.yml, data/en/pmdk.yml, data/en/repoindex.yml, themes/pmem-hugo/layouts/index.html, themes/pmem-hugo/layouts/partials/content/banner.html, themes/pmem-hugo/layouts/pmdk/list.html, themes/pmem-hugo/layouts/pmdk/single.html
- remove banner from the main page
- add banner to the template for all PMDK libraries
- point the place where users can submit issues and ask questions
- simplify the repoindex data structure in preparation for the upcoming refresh (a done-by-the-way change)
Preview:
- mainpage: https://janekmi.github.io/ (no banner)
- /pmdk: https://janekmi.github.io/pmdk/ (updated banner)
- https://janekmi.github.io/pmdk/libpmemobj/ (banner in the header of an exemplar library)
- https://janekmi.github.io/pmdk/manpages/linux/master/libpmemobj/libpmemobj.7/ (manpage example)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/371)
=> common: end up the winding down period

.github/workflows/gh-pages.yml
Based on the provided example: https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml
And confirmed to work on my fork:
- https://github.com/janekmi/janekmi.github.io/actions/runs/6038873451
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/377)
=> common: replace the deployment action since the current one does not allow increasing the timeout

content/blog/2022/update-pmdk-project-status.md, content/rpma/_index.md
Preview:
https://grom72.github.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/378)
=> doc: rpma discontinuation announcement
