pmem/pmem.github.io

_posts/2014-09-23-btt.md

btt post: fixed broken link

---

_posts/2015-06-02-obj-mysql.md
_posts/2015-06-11-type-safety-macros.md
_posts/2015-06-13-accessing-pmem.md
_posts/2015-06-15-transactions.md
_posts/2015-06-16-types.md
_posts/2015-06-17-tx-alloc.md
_posts/2015-06-18-ntx-alloc.md
_posts/2015-06-18-threads.md
_posts/2015-06-19-lists.md
_posts/2015-07-17-pmemcheck-basic.md
_posts/2015-07-20-pmemcheck-transactions.md
css/pygment_trac.css

- add two blog posts on Valgrind pmemcheck
- small highlight style modifications
- update code blocks in previous posts

pmemcheck blog posts

---

_posts/2015-09-10-kvstore2.md

This blog post is related to pulls #399 and #400.

obj: add kv-store part 2 post

---

_posts/2014-09-09-git-workflow.md

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/29)

blog: add c++ info to git workflow blog post

---

_layouts/post.html
_posts/2015-06-02-obj-mysql.md
_posts/2015-06-11-type-safety-macros.md
_posts/2015-06-12-pmem-model.md
_posts/2015-06-13-accessing-pmem.md
_posts/2015-06-15-transactions.md
_posts/2015-06-16-types.md
_posts/2015-06-17-tx-alloc.md
_posts/2015-06-18-ntx-alloc.md
_posts/2015-06-18-threads.md
_posts/2015-06-19-lists.md
_posts/2015-07-17-pmemcheck-basic.md
_posts/2015-07-20-pmemcheck-transactions.md
_posts/2015-07-31-diy-kvstore.md
_posts/2015-09-10-kvstore2.md
_posts/2015-09-16-mt-tx.md
_posts/2015-09-29-pmemobjfs.md
_posts/2015-10-20-lockfree-vector.md
_posts/2015-11-23-replication-intro.md
_posts/2015-12-15-performance.md
_posts/2016-01-12-cpp-01.md
_posts/2016-01-12-cpp-02.md
_posts/2016-01-12-cpp-03.md
_posts/2016-01-12-cpp-04.md
_posts/2016-02-22-pm-emulation.md
_posts/2016-02-25-fragmentation.md

This patchset will allow authors to opt-in for comments by specifying identifier field in their posts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/37)

Add disqus comments support to blogs

---

_posts/2016-05-10-cpp-05.md

This is the first in a series of cpp posts. It can be viewed directly on my page:
http://tomaszkapela.github.io/2016/05/10/cpp-05.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/38)

cpp: add blog post on pool wrapper

---

_posts/2016-05-19-cpp-06.md

Allocations in C++. A more readable version can be found at:
http://tomaszkapela.github.io/2016/05/19/cpp-06.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/39)

cpp: post on make_persistent

---

css/manual.css

wlemkows.github.io
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/41)

Added css to manpages

---

_posts/2016-05-25-cpp-07.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/42)

cpp: transactions blog entry

---

_posts/2016-05-31-cpp-08.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/43)

cpp: blog on synchronization mechanisms

---

_posts/2016-06-02-cpp-ctree-conversion.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/44)

cpp: ctree conversion post

---

_posts/2015-06-18-ntx-alloc.md
_posts/2015-06-19-lists.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/46)

update tutorials to include new style constructor

---

_posts/2016-02-22-pm-emulation.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/47)

Kernel configuration options update with 4.6 features

---

about/index.md
index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/49)

doc: remove 'Linux' from NVM Library name

---

glossary/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/50)

Mention 3D XPoint near other technologies

---

_posts/2016-12-20-libpmemobj-year-in-review.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/51)

add year 2016 in review post

---

_posts/2016-12-20-libpmemobj-year-in-review.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/53)

fix issues of year in review post

---

_posts/2016-12-21-windows-nvml.md

this is my first attempt at submitting a blog entry so be gentile on me :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/52)

blog: add post describing Windows support

---

_posts/2017-01-23-cpp-strings.md

I struggled to figure this out in working on the KV prototype, so figured this would make a good post.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/55)

blog: modeling strings with cpp bindings

---

_posts/2017-01-25-libpmemobj-jan-plans.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/56)

add libpmemobjs Q1 plans post

---

_posts/2017-03-29-progress-report-q1-17.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/61)

add q1 2017 progress report

---

css/manual.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/63)

doc: shortcut versions css

---

_posts/2017-07-04-progress-report-q2-17.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/64)

add Q2 progress report

---

_posts/2017-07-10-cpp-containers.md

Blog post explaining the approach taken to enable persistent memory
friendly containers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/65)

cpp: blog post on the allocator

---

_posts/2017-10-05-progress-report-q3-17.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/66)

add Q3 progress report

---

css/manual.css

http://wlemkows.github.io
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/67)

doc: css update

---

Gemfile
_posts/2014-08-25-creating-pmem-io.md

Also includes adding a json dependency to the Gemfile,
which appears to be required for F26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/68)

update blog post showing how to configure jekyll

---

_posts/2016-01-12-cpp-04.md
_posts/2016-06-02-cpp-ctree-conversion.md

Please merge *after* pmem/pmdk#2503.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/72)

Update references to C++ examples.

---

_layouts/default.html
_layouts/post.html
_layouts/redirect.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/75)

doc: update page titles

---

_posts/2018-06-25-fio-tutorial.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/79)

add missing highlight

---

_posts/2016-01-12-cpp-04.md
_posts/2016-06-02-cpp-ctree-conversion.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/81)

Change links in cpp posts to point to new repo

---

_posts/2018-10-22-release-1-5.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/84)

add 1.5 release blog

---

_posts/2018-11-02-cpp-array.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/86)

Post describing pmem::obj::array

---

_posts/2018-11-20-cpp-persistent-containers.md

generated blog post preview:
https://szyrom.github.io/2018/11/20/cpp-persistent-containers.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/88)

Blog post about C++ containers

---

_posts/2018-11-19-bad-blocks.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/89)

Blog on bad blocks

---

_posts/2018-12-05-pool-features.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/91)

blog: Pool features

---

_posts/2019-01-22-extended-memcpy.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/92)

Blog on new memcpy APIs.

---

_posts/2019-02-01-pool-conversion-tool.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/94)

add pool conversion tool blogpost

---

_posts/2019-02-04-pmreorder-basics.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/93)

Blog: pmreorder-basics

---

_posts/2019-02-20-cpp-vector.md

preview:
https://szyrom.github.io/2019/02/20/cpp-vector.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/96)

blog post about C++ pmem::obj::vector

---

_posts/2019-02-01-pool-conversion-tool.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/98)

blog: fix auto numbered list in convert blog

---

_posts/2019-02-04-pmreorder-basics.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/100)

 blog: pmreorder: add -q option to valgrind

---

_posts/2019-05-07-libvmemcache.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/101)

blog: add libvmemcache blog

---

_posts/2019-06-12-two-level-vmemcache.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/102)

blog: add multi-level vmemcache usage

---

_posts/2019-02-04-pmreorder-basics.md

Fix check_consistency() example in _posts/2019-02-04-pmreorder-basics.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/104)

Fix check_consistency() example

---

book/index.html

Users were being registered but received a failure error.  This was due to CORS.  Fixed it using some JQuery since MailChimp doesn't support XHR form submissions directly.
The signup form now disappears upon successful registration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/106)

Fixed signup form CORS issue

---

book/index.html

Created a link to the [Chapter Feedback & Discussion - "Programming Persistent Memory: A Comprehensive Guide for Developers" Book
](https://groups.google.com/forum/#!topic/pmem/5hTR3PHvOLQ) Google Forum
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/107)

Added Google Forum Discussion Link

---

repoindex.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/112)

minor adjustments

---

_posts/2019-10-11-release-1-7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/113)

add PMDK release blog

---

_posts/2019-10-31-vmem-split.md

A short note about what's happening with VMEM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/114)

blog: vmem split

---

repoindex.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/116)

add dev-utils-kit to repoindex

---

book/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/119)

Fix broken link to apress website

---

_posts/2019-12-19-performance.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/122)

performance story fixes

---

_posts/2020-01-20-libmemkind.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/118)

blog: libmemkind intro

---

_posts/2019/2019-12-19-performance.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/129)

add link to part 2 in part 1 of 300ns

---

book/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/136)

Added Google Analytics and Open Graph metadata tags

---

book/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/137)

Add Google Tag Manager Code.

---

book/js/custom.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/138)

[Book] Added Stack Overflow Tracking.

---

_posts/2020/2020-03-04-pmemkv-bindings.md
_posts/2020/2020-05-27-llpl-intro1.md

and link blog posts for llpl and pmemkv-java.
preview: https://lukaszstolarczuk.github.io/2020/03/04/pmemkv-bindings.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/140)

update blog post with latest pmemkv-java release

---

_posts/2020/2020-08-20-pmdk-pvs-studio.md

The rendered version of a post is available here: https://michalbiesek.github.io/2020/08/20/pmdk-pvs-studio.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/141)

PMDK static analyzer post

---

_posts/2020/2020-08-20-pmdk-pvs-studio.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/142)

Fix typo: duplicate "support" word

---

repoindex.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/145)

common: librpma's comment "in development" removed

---

_posts/2020/2020-10-30-pmemkv-java-binding.md

preview: https://karczex.github.io/2020/10/30/pmemkv-java-binding.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/146)

Add pmemkv java binding blog post

---

repoindex.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/150)

update repoindex with new pmdk library and new tools repo name

---

nvml/cpp_obj/index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/153)

update libpmemobj-cpp redirect link

---

_posts/2021/2021-02-11-hazelcast_memkind.md

Required:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/152)

Provide cross-reference link to Hazelcast Blog

---

glossary/index.md
glossary/kmem-dax/_definition
glossary/kmem-dax/_term

Preview: https://michalbiesek.github.io/glossary/#kmem-dax
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/155)

Add KMEM DAX to glossary

---

repoindex.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/156)

add kvdk to repoindex under pmem-aware software category

---

index.md
pmdksummit2021/index.html

- remove dangling </b> tag,
- fix repeated wording.
See the issue here: https://pmem.io/
Fixed here: https://lukaszstolarczuk.github.io/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/159)

fix minor issues

---

glossary/libpmemblk/_definition

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/161)

Fix typo: duplicate "library" word

---

_posts/2018/2018-05-15-using_persistent_memory_devices_with_the_linux_device_mapper.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/162)

Fix a typo in CONFIG_HUGETLB_PAGE

---

repoindex.md

add pmem_rocksdb_plugin to repoindex.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/168)

add pmem_rocksdb_plugin

---

.github/workflows/gh-pages.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/171)

update hugo version

---

content/solutions/linux-kernel-memory-tiering.md

Fixes #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/176)

Fix typo in Linux Kernel Memory Tiering solution

---

content/solutions/memkind-tiering.md

Fixes #175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/177)

Fixes typo in description for 'MemTier'

---

content/blog/2014/nvm-library-overview.md
content/blog/2015/accessing-pmem.md
content/blog/2015/lists.md
content/blog/2015/ntx-alloc.md
content/blog/2015/threads.md
content/blog/2015/transactions.md
content/blog/2015/tx-alloc.md
content/blog/2015/types.md
content/blog/2018/cpp-array.md
content/blog/2018/cpp-persistent-containers.md
content/blog/2019/cpp-vector.md
content/blog/2020/libmemkind.md
content/blog/2020/memkind-dax-kmem.md
content/blog/2021/concurrency.md
content/blog/2021/how-to-contribute-to-pmem-io.md
data/en/about.yml
data/en/code_samples.yml
data/en/dev_hub.yml
data/en/repoindex.yml
static/CONTRIBUTING.md

- update some links,
- fix minor issues,
- add missing repos in repoindex,
- unify some blog categories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/173)

various minor fixes

---

.gitignore

get rid of all temp or IDE files (e.g. '.hugo_build.lock').
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/180)

Extend gitignore for all files starting with '.'

---

.github/ISSUE_TEMPLATE/pmem-solution-request.md

Adds a custom Issue template to capture all the required information when adding a new product/solution to the repository. Also adds detailed info for reviewers and submitters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/179)

Add a new "PMem Solution Request" template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add a Bug and 'Request for Enhancement/Feature Request' templates to GitHub to support the new pmem.io refresh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/165)

Add Bug and RFE issue templates

---

content/announcements/2021/Memkind-1-13-0-release.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/185)

Add memkind 1.13.0 release announcement

---

data/en/solutions.yml

Fixes: #178
// working preview: https://lukaszstolarczuk.github.io/solutions/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/186)

Link "Show your work" with a new issue template on GitHub

---

config.toml
content/announcements/2021/MemKind-1-11-0-release.md
content/announcements/2021/MemKind-1-12-0-release.md
content/announcements/2021/Memkind-1-13-0-release.md
content/events/2021-SPDK-PMDK-Intel-performance-analyzers-virtual-forum.md
content/solutions/memkind-tiering.md

this will fix issue #188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/190)

Fix MemKind -> Memkind typo

---

config.toml

this will fix #189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/191)

Replace link to MemKeyDB with a link to TieredMemDB

---

content/rpma/manpages/master/librpma.7.md
content/rpma/manpages/v0.10.0/librpma.7.md
content/rpma/manpages/v0.11.0/librpma.7.md
content/rpma/manpages/v0.9.0/librpma.7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/202)

rpma: fix links to the article

---

content/events/2022-SNIA-Persistent-Memory-Summit.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/211)

Add SNIA Persistent Memory and Computational Storage Summit 2022 Event

---

content/blog/2022/async.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/212)

fix a few issues in the miniasync blog post

---

content/rpma/_index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/218)

rpma: display exact link to source code of librpma

---

content/rpma/_index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/217)

rpma: change format of links to the MD one

---

layouts/shortcodes/manpages.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/219)

replace the use of depracated hugo function

---

content/rpma/documentation/perf-tuning.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/224)

rpma: update perf-tuning.md for ICX

---

content/rpma/documentation/basic-direct-write-to-pmem.md
content/rpma/documentation/basic-hw_sw_setup_starting_point.md
content/rpma/documentation/perf-tuning.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/225)

rpma: use MD-style links

---

content/rpma/documentation/perf-tuning.md
content/rpma/manpages/v0.9.0/rpma_mr_get_descriptor_size.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/226)

rpma: fix spelling errors in rpma docs

---

content/rpma/documentation/basic-direct-write-to-pmem.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/227)

rpma: update pmem.io benchmarking manuals for ICX

---

content/rpma/documentation/basic-direct-write-to-pmem.md

Move common part to DDIO description to common paragraph
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/232)

rpma: update pmem.io benchmarking manuals for ICX and CLX DDIO

---

data/en/pmdk.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/229)

pmdk: update librpmem information

---

content/blog/2018/cpp-array.md
content/blog/2018/release-1-5.md
content/blog/2019/cpp-vector.md

A small change answering issues raised in https://github.com/pmem/pmem.github.io/pull/238.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/239)

Link fixes - additional patch

---

content/pmdk/manpages/linux/master/libpmem/libpmem.7.md
content/pmdk/manpages/linux/master/libpmem2/libpmem2.7.md
content/pmdk/manpages/linux/master/libpmemblk/libpmemblk.7.md
content/pmdk/manpages/linux/master/libpmemlog/libpmemlog.7.md
content/pmdk/manpages/linux/master/libpmemobj/libpmemobj.7.md
content/pmdk/manpages/linux/master/libpmempool/libpmempool.7.md
content/pmdk/manpages/linux/master/libpmemset/libpmemset.7.md
content/pmdk/manpages/linux/master/librpmem/librpmem.7.md
content/pmdk/manpages/linux/master/libvmem/libvmem.7.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/242)

remove old manpage shortcuts

---

content/blog/2022/masync-ex-hashmap.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/237)

add miniasync hashmap blog post

---

data/en/pmdk.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/254)

librpmem description fix

---

content/blog/2022/similarity-search-opportunity-for-pmem.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/255)

Update similarity search - clarify GraphANN/DiskANN relation and point to Intel article

---

content/announcements/2022/MiniAsync-v0-1-0-release.md
content/announcements/2022/PMDK-v1-12-0-release.md

https://lplewa.github.io//announcements/2022/pmdk-v1-12-0-release/
https://lplewa.github.io//announcements/2022/miniasync-v0-1-0-release/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/249)

add announcements about pmdk and miniasync releases

---

data/en/repoindex.yml

- add new projects and their microsites,
- move pmdk-tests to inactive repos, since we don't develop any more tests there,
- fix rows' numbering.
// Preview: https://lukaszstolarczuk.github.io/repoindex/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/258)

fix repoindex

---

content/announcements/2022/pmemstream-v0-2-0-release.md

// Preview: https://lukaszstolarczuk.github.io/announcements/2022/pmemstream-v0-2-0-release/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/256)

Add pmemstream-0.2.0 release announcement

---

.github/workflows/gh-pages.yml
themes/pmem-hugo/layouts/_default/single.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/259)

update to the latest version of hugo (0.101.0)

---

content/blog/2022/libpmem2-part1.md

//Preview: https://wlemkows.github.io/blog/2022/06/introduction-to-libpmem2-part-1/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/253)

Add libpmem2 part 1 blog post

---

content/announcements/2022/Memkind-v1-14-0-release.md

Preview: https://patkamin.github.io/announcements/2022/memkind-v1-14-0-release/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/279)

Memkind release announcement

---

content/pmemkv-ruby/_index.md
data/en/pmemkv.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/288)

pmemkv: update bindings links and info

---

config.toml
content/memkind/_index.md
content/memkind/manpages/fixedallocator.3.md
content/memkind/manpages/hbwmalloc.3.md
content/memkind/manpages/libmemtier.3.md
content/memkind/manpages/libmemtier.7.md
content/memkind/manpages/memkind.3.md
content/memkind/manpages/memkindallocator.3.md
content/memkind/manpages/pmemallocator.3.md
data/en/memkind.yml
static/css/custom.css
themes/pmem-hugo/layouts/memkind/list.html
themes/pmem-hugo/layouts/memkind/single.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/262)

add memkind sub-page

---

content/memkind/manpages/autohbw.7.md
content/memkind/manpages/fixedallocator.3.md
content/memkind/manpages/hbwallocator.3.md
content/memkind/manpages/hbwmalloc.3.md
content/memkind/manpages/libmemtier.3.md
content/memkind/manpages/libmemtier.7.md
content/memkind/manpages/memkind-auto-dax-kmem-nodes.1.md
content/memkind/manpages/memkind-hbw-nodes.1.md
content/memkind/manpages/memkind.3.md
content/memkind/manpages/memkind_arena.3.md
content/memkind/manpages/memkind_dax_kmem.3.md
content/memkind/manpages/memkind_default.3.md
content/memkind/manpages/memkind_fixed.3.md
content/memkind/manpages/memkind_hbw.3.md
content/memkind/manpages/memkind_hugetlb.3.md
content/memkind/manpages/memkind_interleave.3.md
content/memkind/manpages/memkind_pmem.3.md
content/memkind/manpages/memkindallocator.3.md
content/memkind/manpages/memtier.1.md
content/memkind/manpages/pmemallocator.3.md
data/en/memkind.yml
themes/pmem-hugo/layouts/memkind/list.html

I will categorize the documentation later ;)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/297)

Rest of the memkind documentation

---

content/rpma/reports/_index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/307)

doc: Performance Reports header extension.

---

content/blog/2019/pool-conversion-tool.md
content/pmdk-convert/_index.md

// Preview:
Before:
- https://pmem.io/blog/2019/02/pool-conversion-tool/
- https://pmem.io/pmdk-convert
After:
- https://lukaszstolarczuk.github.io/blog/2019/02/pool-conversion-tool/
- https://lukaszstolarczuk.github.io/pmdk-convert/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/310)

update table style and link blog post in convert description

---

content/blog/2022/update-pmdk-project-status.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/317)

add pmdk update article

---

data/en/memkind.yml
themes/pmem-hugo/layouts/memkind/list.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/316)

Deletion of the binaries section

---

content/blog/2022/update-pmdk-project-status.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/327)

update the information in the blog

---

content/blog/2022/update-pmdk-project-status.md

Preview: https://szadam.github.io//blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/329)

Update the table of the specific support

---

content/blog/2020/libmemkind.md
data/en/memkind.yml

// preview: https://lukaszstolarczuk.github.io/memkind
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/331)

Updates for memkind

---

content/solutions/intel-vtune-platform-profiler.md
content/solutions/intel-vtune-profiler.md

- one image link was incorrect now,
- one title of the VTune utility was "incomplete".
Fixes: #268
// Preview: https://lukaszstolarczuk.github.io/solutions/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/334)

update VTune info

---

content/memkind/manpages/autohbw.7.md
content/memkind/manpages/hbwmalloc.3.md
content/memkind/manpages/libmemtier.7.md
content/memkind/manpages/memkind-auto-dax-kmem-nodes.1.md
content/memkind/manpages/memkind.3.md

make the content up-to-date with current memkind repository state (based on `doc` directory files)
// Previews:
https://lukaszstolarczuk.github.io/memkind/manpages/memkind.3/
https://lukaszstolarczuk.github.io/memkind/manpages/autohbw.7/
https://lukaszstolarczuk.github.io/memkind/manpages/hbwmalloc.3/
https://lukaszstolarczuk.github.io/memkind/manpages/libmemtier.7/
https://lukaszstolarczuk.github.io/memkind/manpages/memkind-auto-dax-kmem-nodes.1/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/336)

memkind: update manpages content

---

content/pmdk/libpmem2.md
data/en/pmdk.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/341)

pmdk: set async as deprecated

---

content/libpmemobj-cpp/_index.md
content/pmdk-convert/_index.md
content/pmdk/libpmemblk.md
content/pmdk/libpmemlog.md
content/pmdk/libpmemset.md
content/pmdk/librpmem.md
content/pmdk/libvmem.md
content/pmdk/libvmmalloc.md
content/pmemkv-java/_index.md
content/pmemkv-nodejs/_index.md
content/pmemkv-python/_index.md
content/pmemkv-ruby/_index.md
content/vmemcache/_index.md
data/en/miniasync.yml
data/en/pmdk.yml
data/en/pmemkv.yml
data/en/pmemstream.yml
data/en/repoindex.yml
themes/pmem-hugo/layouts/miniasync/list.html
themes/pmem-hugo/layouts/pmdk/list.html
themes/pmem-hugo/layouts/pmemkv/list.html
themes/pmem-hugo/layouts/pmemstream/list.html
themes/pmem-hugo/layouts/repoindex/list.html

Previews:
https://szadam.github.io/pmemstream/
https://szadam.github.io/pmdk
https://szadam.github.io/miniasync
https://szadam.github.io/pmemkv
...
https://szadam.github.io/repoindex
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/330)

Add information about the discontinuation of the projects

---

content/blog/2022/update-pmdk-project-status.md
data/en/repoindex.yml

preview:
https://szadam.github.io/repoindex/
https://szadam.github.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/343)

Add information about the discontinuation of the vltrace and pynvm

---

content/pmdk/libpmem.md
content/pmdk/libpmem2.md
content/pmdk/libpmemobj.md
content/pmdk/libpmempool.md
content/pmdk/pmempool.md
data/en/pmdk.yml

[pmem/pmdk](https://github.com/pmem/pmdk/pull/5553)
[pmem/pmdk](https://github.com/pmem/pmdk/pull/5557)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/344)

pmdk: set Windows and FreeBSD support as deprecated

---

content/pmdk/libpmem.md

content and description of these examples were outdated. Make it in-line with examples' version from current PMDK master.
Fixes: https://github.com/pmem/pmdk/issues/4205
// Preview:
before: https://pmem.io/pmdk/libpmem/
after: https://lukaszstolarczuk.github.io/pmdk/libpmem/
manpage example: https://github.com/pmem/pmdk/blob/master/src/examples/libpmem/manpage.c
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/348)

pmdk: update libpmem examples

---

content/announcements/2022/PMDK-v1-12-0-release.md
content/announcements/2023/PMDK-v1-13-0-release.md

Preview: https://lukaszstolarczuk.github.io//announcements/2023/pmdk-v1-13-0-release/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/353)

add PMDK 1.13.0 announcement

---

content/announcements/2023/PMDK-v2-0-0-release.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/366)

Add PMDK 2.0.0 announcement

---

data/en/repoindex.yml
themes/pmem-hugo/layouts/repoindex/list.html

Preview: https://janekmi.github.io/repoindex/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/372)

repoindex: apply post-winding-down changes

---

content/announcements/2023/PMDK-100p-GitHub.md
content/announcements/2023/PMDK-v1-13-1-release.md

Preview:
- Homepage: https://janekmi.github.io/
- Announcement: https://janekmi.github.io/announcements/2023/pmdk-100p-github/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/373)

pmdk: has gone 100% GitHub

---

themes/pmem-hugo/layouts/announcements/list.html

Preview: https://janekmi.github.io/announcements/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/374)

announcements: ungroup

---

.github/workflows/gh-pages.yml
content/tutorials/Create-a-Persistent-Memory-Aware-Queue-Using-the-Persistent-Memory-Development-Kit.md

Reverts pmem/pmem.github.io#382
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmem.github.io/383)

Revert "Update hugo"
